-- ============================================================
-- 展場 POS 系統 — 資料表結構 (Schema) — 與正式庫對齊的 baseline
-- 來源：000 / 000b 對正式資料庫的反向匯出 (2026-06)。
--
-- ⚠️ 用途：在「全新空白資料庫」(例如 staging clone) 從零重建。
--    請勿對既有正式庫執行 —— 表已存在會被略過，且本檔僅描述結構不含資料。
--
-- 忠實對齊重點：
--   * id 皆為 bigint GENERATED BY DEFAULT AS IDENTITY。
--   * 價格/數量/庫存皆為 bigint；日期為 timestamptz。
--   * 多數欄位 nullable (反映正式庫現況)；無 XOR、無 is_active。
--   * 僅有 PK 與 FK；正式庫沒有任何 UNIQUE 約束 (order_token/Uid 等皆無)。
--   * 僅 Exhibition_Product_Details.booth_id 的 FK 為 ON DELETE CASCADE，其餘為 NO ACTION。
--   * Bundle_Items 保留 share_weight (numeric, 預設 1)；各表保留 created_at。
--   * Exhibition_Booths 已含通販 (permanent) 支援：exhibition_id 可為 NULL +
--     booth_type + name (對應 004_permanent_booth 增量 migration)。
-- 執行順序：001_schema → 002_functions → 003_rls
-- ============================================================

-- 1. 人員 Users
CREATE TABLE IF NOT EXISTS "Users" (
  "id"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nickname"  text NOT NULL,
  "is_seller" boolean NOT NULL,
  "is_owner"  boolean NOT NULL,
  "Uid"       uuid REFERENCES auth.users (id)
);

-- 2. 展覽 Exhibitions
CREATE TABLE IF NOT EXISTS "Exhibitions" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"       text NOT NULL,
  "start_date" timestamptz NOT NULL,
  "end_date"   timestamptz NOT NULL,
  "location"   text NOT NULL,
  "link"       text
);

-- 3. 商品 Products
CREATE TABLE IF NOT EXISTS "Products" (
  "id"              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "seller_id"       bigint NOT NULL REFERENCES "Users" (id),
  "created_at"      timestamptz NOT NULL DEFAULT now(),
  "name"            text NOT NULL,
  "original_price"  bigint,
  "total_inventory" bigint
);

-- 4. 商品授權 Product_Permissions
--    (注意：owner_id 的 FK 在正式庫名為 Product_Permissions_seller_id_fkey)
CREATE TABLE IF NOT EXISTS "Product_Permissions" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint NOT NULL REFERENCES "Products" (id),
  "owner_id"   bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "enable"     boolean NOT NULL,
  CONSTRAINT "Product_Permissions_seller_id_fkey"
    FOREIGN KEY ("owner_id") REFERENCES "Users" (id)
);

-- 5. 展覽攤位 Exhibition_Booths
--    booth_type='exhibition' 需綁展覽；'permanent'(通販) 無展覽、無期效、永遠可編輯。
CREATE TABLE IF NOT EXISTS "Exhibition_Booths" (
  "id"            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exhibition_id" bigint REFERENCES "Exhibitions" (id),
  "owner_id"      bigint NOT NULL REFERENCES "Users" (id),
  "booth_number"  text,
  "booth_type"    text NOT NULL DEFAULT 'exhibition',
  "name"          text,  -- 通販攤位自帶名稱
  CONSTRAINT "booth_type_check"
    CHECK ("booth_type" IN ('exhibition', 'permanent')),
  CONSTRAINT "booth_type_consistency"
    CHECK (
      ("booth_type" = 'exhibition' AND "exhibition_id" IS NOT NULL)
      OR
      ("booth_type" = 'permanent'  AND "exhibition_id" IS NULL AND "name" IS NOT NULL)
    )
);

-- 6. 組合包 Product_Bundles  (正式庫無 is_active)
CREATE TABLE IF NOT EXISTS "Product_Bundles" (
  "id"       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booth_id" bigint NOT NULL REFERENCES "Exhibition_Booths" (id),
  "name"     text NOT NULL
);

-- 7. 組合包內含商品 Bundle_Items  (保留 share_weight)
CREATE TABLE IF NOT EXISTS "Bundle_Items" (
  "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bundle_id"    bigint NOT NULL REFERENCES "Product_Bundles" (id),
  "product_id"   bigint NOT NULL REFERENCES "Products" (id),
  "share_weight" numeric DEFAULT 1
);

-- 8. 展覽攤位商品明細 Exhibition_Product_Details
--    (booth_id 的 FK 為 ON DELETE CASCADE；product_id / bundle_id 二擇一但無 DB 約束)
CREATE TABLE IF NOT EXISTS "Exhibition_Product_Details" (
  "id"          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booth_id"    bigint NOT NULL REFERENCES "Exhibition_Booths" (id) ON DELETE CASCADE,
  "product_id"  bigint REFERENCES "Products" (id),
  "event_price" bigint,
  "is_paid"     boolean DEFAULT false,
  "bundle_id"   bigint REFERENCES "Product_Bundles" (id)
);

-- 9. 交易訂單 Orders  (order_number / order_token 皆「無」UNIQUE)
CREATE TABLE IF NOT EXISTS "Orders" (
  "id"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at"   timestamptz NOT NULL DEFAULT now(),
  "order_number" text,
  "booth_id"     bigint NOT NULL REFERENCES "Exhibition_Booths" (id),
  "phone"        text,
  "method"       text NOT NULL,
  "order_token"  uuid DEFAULT gen_random_uuid()
);

-- 10. 銷售紀錄 Sales_Records  (正式庫「無」method 欄)
CREATE TABLE IF NOT EXISTS "Sales_Records" (
  "id"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "detail_id"  bigint NOT NULL REFERENCES "Exhibition_Product_Details" (id),
  "quantity"   bigint NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "order_id"   bigint REFERENCES "Orders" (id)
);
